---

- name: Configuring NRPE daemon
  template:
    src: "{{ item }}"
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.monitored/nrpe.cfg.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.monitored/nrpe.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.monitored/nrpe.cfg.j2"
    - "inventory/group_files/servers/honzamach.monitored/nrpe.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.monitored/nrpe.cfg.j2"
    - "nrpe.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "nrpe.cfg.j2"
  notify: Restart NRPE service

- name: Installing local NRPE daemon configurations
  template:
    src: "{{ item }}"
    dest: /etc/nagios/nrpe.d/local.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.monitored/nrpe_local.cfg.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.monitored/nrpe_local.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.monitored/nrpe_local.cfg.j2"
    - "inventory/group_files/servers/honzamach.monitored/nrpe_local.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.monitored/nrpe_local.cfg.j2"
    - "nrpe_local.cfg.{{ ansible_lsb['codename'] }}.j2"
    - "nrpe_local.cfg.j2"
  notify: Restart NRPE service
  when: hm_monitored__local_commands|length

- name: Ensuring NRPE daemon is running and enabled at system start
  service:
    name: "{{ hm_monitored__service_name }}"
    state: started
    enabled: yes

- name: Managing system-status script
  template:
    src: "{{ item }}"
    dest: /opt/system-status/system-status
    owner: root
    group: root
    mode: 0755
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.monitored/system-status.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.monitored/system-status.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.monitored/system-status.j2"
    - "inventory/group_files/servers/honzamach.monitored/system-status.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.monitored/system-status.j2"
    - "system-status.{{ ansible_lsb['codename'] }}.j2"
    - "system-status.j2"

- name: Managing system-status script installation
  file:
    src: /opt/system-status/system-status
    dest: /usr/local/bin/system-status
    state: link

- name: Managing system status utility subdirectory
  file:
    path: /opt/system-status/system-status.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Managing system-status-local script
  template:
    src: "{{ item }}"
    dest: /opt/system-status/system-status.d/10-local
    owner: root
    group: root
    mode: 0755
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.monitored/system-status-local.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.monitored/system-status-local.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.monitored/system-status-local.j2"
    - "inventory/group_files/servers/honzamach.monitored/system-status-local.{{ ansible_lsb['codename'] }}.j2"
    - "inventory/group_files/servers/honzamach.monitored/system-status-local.j2"
    - "system-status-local.{{ ansible_lsb['codename'] }}.j2"
    - "system-status-local.j2"
  when: hm_monitored__local_commands|length

- name: Removing system-status-local script
  file:
    path: /opt/system-status/system-status.d/10-local
    state: absent
  when: not hm_monitored__local_commands|length
